
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 17 04:36:52 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 24;
  public static final int CONST = 3;
  public static final int LPAREN = 26;
  public static final int SEMI = 5;
  public static final int CONTINUE = 12;
  public static final int LESS = 33;
  public static final int RPAREN = 27;
  public static final int GRE = 31;
  public static final int BOTTLINE = 7;
  public static final int AND = 35;
  public static final int RECORD = 45;
  public static final int DIFFER = 30;
  public static final int OR = 36;
  public static final int COMMA = 4;
  public static final int CLASS = 15;
  public static final int INC = 43;
  public static final int DIV = 40;
  public static final int DIGIT = 47;
  public static final int PLUS = 37;
  public static final int MIN = 38;
  public static final int LESSEQ = 34;
  public static final int IF = 20;
  public static final int DOT = 42;
  public static final int BOOLEAN = 48;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int RBRACKET = 25;
  public static final int EQUAL = 28;
  public static final int NEW = 6;
  public static final int error = 1;
  public static final int MUL = 39;
  public static final int DASH = 8;
  public static final int MOD = 41;
  public static final int IDENT = 49;
  public static final int BREAK = 11;
  public static final int VOID = 14;
  public static final int SAME = 29;
  public static final int LBRACE = 22;
  public static final int ELSE = 21;
  public static final int LETTER = 46;
  public static final int READ = 18;
  public static final int GOTO = 19;
  public static final int WHILE = 10;
  public static final int RBRACE = 23;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int GREEQ = 32;
  public static final int DEC = 44;
  public static final int PRINT = 17;
  public static final int DO = 9;
}

